// Builds one HTML page per CV variant from cv/content.mjs into cv/build/.
// scripts/cv-pdf.sh then prints each page to public/cv/*.pdf.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { common, variants } from "./content.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "build");
mkdirSync(out, { recursive: true });

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
// content strings may carry a little inline markup: *italic* and [text](url)
const inline = (s) => esc(s)
  .replace(/\*(.+?)\*/g, "<i>$1</i>")
  .replace(/\[(.+?)\]\((.+?)\)/g, '<a class="link" href="$2">$1</a>');

const bullets = (items) => `<ul class="b">\n${items.map((b) => `    <li>${inline(b)}</li>`).join("\n")}\n  </ul>`;

function entry({ when, what, sub, points, line }) {
  const subHtml = sub ? `<span class="sub"> ${inline(sub)}</span>` : "";
  const body = points ? bullets(points) : `<p class="soft">${inline(line)}</p>`;
  return `<div class="entry"><span class="when">${esc(when)}</span><div>
  <p class="what">${inline(what)}${subHtml}</p>
  ${body}</div></div>`;
}

const list = (items) => `<ul class="l">\n${items.map(([lead, rest]) => `      <li><b>${inline(lead)}</b>${inline(rest)}</li>`).join("\n")}\n    </ul>`;

const pick = (map, keys) => keys.map((k) => map[k]);

const HEAD = {
  en: { profile: "Profile", education: "Education", experience: "Experience", projects: "Projects", skills: "Skills",
    awards: "Awards, programmes &amp; certificates", publication: "Publication", leadership: "Leadership &amp; involvement" },
  tr: { profile: "Profil", education: "Eğitim", experience: "Deneyim", projects: "Projeler", skills: "Yetkinlikler",
    awards: "Ödüller, programlar ve sertifikalar", publication: "Yayın", leadership: "Liderlik ve topluluk" },
};

// a variant in another language brings its own wording of the shared data in `text`
function withText(common, text = {}) {
  const out = { ...common, ...text };
  for (const k of ["experience", "projects", "awards", "publication", "leadership"]) {
    out[k] = { ...common[k], ...(text[k] || {}) };
  }
  return out;
}

function page(v) {
  const c = withText(common, v.text);
  const h = HEAD[v.lang || "en"];
  const pub = v.publication || c.defaults.publication;
  const links = c.links.filter((l) => v.links.includes(l.key));
  const exp = v.experience.map((key) => entry({ ...c.experience[key], points: v.points[key] }));
  // new graduate order: Education (with the ÖRS project) comes before Experience
  const projOf = (key) => {
    const p = c.projects[key];
    return entry(v.points[key] ? { ...p, points: v.points[key] } : p);
  };
  const ors = v.projects.includes("ors") ? projOf("ors") : "";
  const proj = v.projects.filter((k) => k !== "ors").map((key) => {
    const p = c.projects[key];
    return entry(v.points[key] ? { ...p, points: v.points[key] } : p);
  });
  const skills = v.skills.map(([k, val]) => `<dt>${esc(k)}</dt><dd>${inline(val)}</dd>`).join("\n");
  return `<!doctype html>
<html lang="${v.lang || "en"}">
<head>
<meta charset="utf-8">
<title>Tolga Çakan · CV · ${esc(v.label.en)}</title>
<!-- Generated by cv/build.mjs from cv/content.mjs. Do not edit by hand. -->
<link rel="stylesheet" href="../style.css">
</head>
<body>

<div class="namebar">${v.photo ? `<img class="photo" src="../../public/tolga.png" alt="">` : ""}<h1>${esc(c.name)}</h1><span class="place">${esc(c.place)} · ${esc(c.born)}</span></div>
<p class="title">${inline(v.title)}</p>
<div class="contact">
  <a class="port" href="${c.portfolio.href}">${esc(c.portfolio.label)}</a>
  <a href="mailto:${c.email}">${esc(c.email)}</a>
  <a href="${c.phone.href}">${esc(c.phone.label)}</a>
${links.map((l) => `  <a href="${l.href}">${esc(l.label)}</a>`).join("\n")}
</div>

<h2>${h.profile}</h2>
<p class="summary">${inline(v.profile)}</p>

<h2>${h.education}</h2>
${entry(c.degree)}
${ors}

<h2>${h.experience}</h2>
${exp.join("\n")}

<h2>${h.projects}</h2>
${proj.join("\n")}

<h2>${h.skills}</h2>
<dl class="skills">
${skills}
</dl>

<div class="cols">
  <div>
    <h2>${h.awards}</h2>
    ${list(pick(c.awards, v.awards || c.defaults.awards))}
${pub === "none" ? "" : `    <h2>${h.publication}</h2>
    ${list([c.publication[pub]])}`}
  </div>
  <div>
    <h2>${h.leadership}</h2>
    ${list(pick(c.leadership, v.leadership || c.defaults.leadership))}
  </div>
</div>

</body>
</html>
`;
}

for (const v of variants) {
  writeFileSync(join(out, `${v.slug}.html`), page(v));
  console.log(`cv/build/${v.slug}.html`);
}
