// Builds one HTML page per CV variant from cv/content.mjs into cv/build/.
// scripts/cv-pdf.sh then prints each page to public/cv/*.pdf.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { common, variants } from "./content.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "build");
mkdirSync(out, { recursive: true });

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
// content strings may carry a little inline markup: *italic* and [text](url)
const inline = (s) => esc(s)
  .replace(/\*(.+?)\*/g, "<i>$1</i>")
  .replace(/\[(.+?)\]\((.+?)\)/g, '<a class="link" href="$2">$1</a>');

const bullets = (items) => `<ul class="b">\n${items.map((b) => `    <li>${inline(b)}</li>`).join("\n")}\n  </ul>`;

function entry({ when, what, sub, points, line }) {
  const subHtml = sub ? `<span class="sub"> ${inline(sub)}</span>` : "";
  const body = points ? bullets(points) : `<p class="soft">${inline(line)}</p>`;
  return `<div class="entry"><span class="when">${esc(when)}</span><div>
  <p class="what">${inline(what)}${subHtml}</p>
  ${body}</div></div>`;
}

const list = (items) => `<ul class="l">\n${items.map(([lead, rest]) => `      <li><b>${inline(lead)}</b>${inline(rest)}</li>`).join("\n")}\n    </ul>`;

const pick = (map, keys) => keys.map((k) => map[k]);

function page(v) {
  const c = common;
  const pub = v.publication || c.defaults.publication;
  const links = c.links.filter((l) => v.links.includes(l.key));
  const exp = v.experience.map((key) => entry({ ...c.experience[key], points: v.points[key] }));
  const proj = v.projects.map((key) => {
    const p = c.projects[key];
    return entry(v.points[key] ? { ...p, points: v.points[key] } : p);
  });
  const skills = v.skills.map(([k, val]) => `<dt>${esc(k)}</dt><dd>${inline(val)}</dd>`).join("\n");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Tolga Çakan · CV · ${esc(v.label.en)}</title>
<!-- Generated by cv/build.mjs from cv/content.mjs. Do not edit by hand. -->
<link rel="stylesheet" href="../style.css">
</head>
<body>

<h1>${esc(c.name)}</h1>
<p class="title">${inline(v.title)}</p>
<div class="contact">
  <a class="port" href="${c.portfolio.href}">${esc(c.portfolio.label)}</a>
  <span>${esc(c.place)}</span>
  <a href="mailto:${c.email}">${esc(c.email)}</a>
  <a href="${c.phone.href}">${esc(c.phone.label)}</a>
${links.map((l) => `  <a href="${l.href}">${esc(l.label)}</a>`).join("\n")}
</div>

<h2>Profile</h2>
<p class="summary">${inline(v.profile)}</p>

<h2>Experience</h2>
${exp.join("\n")}

<h2>${esc(v.projectsHeading || "Projects")}</h2>
${proj.join("\n")}

<h2>Skills</h2>
<dl class="skills">
${skills}
</dl>

<div class="cols">
  <div>
    <h2>Education</h2>
    ${list(c.education)}
    <h2>Awards, programmes &amp; certificates</h2>
    ${list(pick(c.awards, v.awards || c.defaults.awards))}
  </div>
  <div>
    <h2>Leadership &amp; involvement</h2>
    ${list(pick(c.leadership, v.leadership || c.defaults.leadership))}
${pub === "none" ? "" : `    <h2>Publication</h2>
    ${list([c.publication[pub]])}`}
  </div>
</div>

</body>
</html>
`;
}

for (const v of variants) {
  writeFileSync(join(out, `${v.slug}.html`), page(v));
  console.log(`cv/build/${v.slug}.html`);
}
